### ISSUE TITLE
Player Loading

### ISSUE THREAD

**Issue by s2t2** [debate-watch/debate-watch#1]
Upon initial page load, sometimes the player doesn't load.

![screenshot 2015-08-06 21 15 20](https://cloud.githubusercontent.com/assets/1328807/9145746/e18bfaa4-3d24-11e5-8338-ebf8b74bcff0.png)

It should load without fail, and with minimal-to-no delay..

Page refreshes and subsequent page loads resolve the issue.

**Comment by s2t2** [comment]
Error details and diagnosis:

Sometimes player doesn't start...

``` js
player.playVideo()
Uncaught TypeError: Cannot read property 'postMessage' of null
    at P.g.K (http://s.ytimg.com/yts/jsbin/www-widgetapi-vfl3rOIuQ/www-widgetapi.js:24:326)
    at S (http://s.ytimg.com/yts/jsbin/www-widgetapi-vfl3rOIuQ/www-widgetapi.js:19:449)
    at P.(anonymous function).pb.(anonymous function) [as playVideo] (http://s.ytimg.com/yts/jsbin/www-widgetapi-vfl3rOIuQ/www-widgetapi.js:29:278)
    at <anonymous>:2:8
    at Object.InjectedScript._evaluateOn (<anonymous>:905:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:838:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```

Other times player goes into a playing but un-started state and player position is stuck at a fraction of a second...

``` js
YT.PlayerState
Object {UNSTARTED: -1, ENDED: 0, PLAYING: 1, PAUSED: 2, BUFFERING: 3…}
player.getCurrentTime()
0.57492
```
